INSERT INTO pais (id, bandera, cancion, cancion_youtube, cantante, nombre) VALUES
(1,'suecia_bandera.webp', 'Unforgettable', 'https://www.youtube.com/watch?v=yekc8t0rJqA', 'Marcus & Martinus', 'Suecia'),
(2,'ucrania_bandera.webp', 'Teresa & Maria', 'https://www.youtube.com/watch?v=k_8cNbF8FLI', 'alyona alyona & Jerry Heil', 'Ucrania'),
(3,'alemania_bandera.webp', 'Always On The Run', 'https://www.youtube.com/watch?v=kVOHTxFOhak', 'Isaak', 'Alemania'),
(4,'luxemburgo_bandera.webp', 'Fighter', 'https://www.youtube.com/watch?v=TCWH3Nq5y9A', 'TALI', 'Luxemburgo'),
(5,'paises_bajos_bandera.webp', 'Europapa', 'https://www.youtube.com/watch?v=gT2wY0DjYGo&list=RDEMyShnuIQ-pzWHcilvxBIPJw&start_radio=1', 'Joost Klein', 'Países Bajos'),
(6,'israel_bandera.webp', 'Hurricane', 'https://www.youtube.com/watch?v=lJYn09tuPw4', 'Eden Golan', 'Israel'),
(7,'lituania_bandera.webp', 'Luktelk', 'https://www.youtube.com/watch?v=N8YuQzJLR_k', 'Silvester Belt', 'Lituania'),
(8,'espana_bandera.webp', 'Zorra', 'https://www.youtube.com/watch?v=LJFpexlj9Bs', 'Nebulossa', 'España'),
(9,'estonia_bandera.webp', '(nendest) narkootikumidest ei tea me (küll) midagi', 'https://www.youtube.com/watch?v=zY6RbPaTNUc', '5miinust & Puuluup', 'Estonia'),
(10,'irlanda_bandera.webp', 'Doomsday Blue', 'https://www.youtube.com/watch?v=ZGRXRrlIspY', 'Bambie Thug', 'Irlanda'),
(11,'letonia_bandera.webp', 'Hollow', 'https://www.youtube.com/watch?v=p8FNO0DtBng&list=RDEMGCUTKht6npiEZIaO96FPFg&start_radio=1', 'Dons', 'Letonia'),
(12,'grecia_bandera.webp', 'Zari', 'https://youtube.com/watch?v=XXXXX012', 'Marina Satti', 'Grecia'),
(13,'reino_unido_bandera.webp', 'Dizzy', 'https://www.youtube.com/watch?v=uTYalXf184A', 'Olly Alexander', 'Reino Unido'),
(14,'noruega_bandera.webp', 'Ulveham', 'https://www.youtube.com/watch?v=tFj0p2qIgdE', 'Gåte', 'Noruega'),
(15,'italia_bandera.webp', 'La noia', 'https://www.youtube.com/watch?v=TO85laH-ATY', 'Angelina Mango', 'Italia'),
(16,'serbia_bandera.webp', 'Ramonda', 'https://www.youtube.com/watch?v=tJyBVRBiyKA', 'Teya Dora', 'Serbia'),
(17,'finlandia_bandera.webp', 'No Rules!', 'https://www.youtube.com/watch?v=8Wi7fhswoBA', 'Windows95man', 'Finlandia'),
(18,'portugal_bandera.webp', 'Grito', 'https://www.youtube.com/watch?v=K5wDGhcDSpQ', 'Iolanda', 'Portugal'),
(19,'armenia_bandera.webp', 'Jako', 'https://www.youtube.com/watch?v=Co8ZJIejXBA', 'Ladaniva', 'Armenia'),
(20,'chipre_bandera.webp', 'Liar', 'https://www.youtube.com/watch?v=8q5QozrtEPA', 'Silia Kapsí', 'Chipre'),
(21,'suiza_bandera.webp', 'The Code', 'https://www.youtube.com/watch?v=kiGDvM14Kwg', 'Nemo', 'Suiza'),
(22,'eslovenia_bandera.webp', 'Veronika', 'https://www.youtube.com/watch?v=uWcSsi7SliI', 'Raiven', 'Eslovenia'),
(23,'croacia_bandera.webp', 'Rim Tim Tagi Dim', 'https://www.youtube.com/watch?v=xTBrVNZtnys', 'Baby Lasagna', 'Croacia'),
(24,'georgia_bandera.webp', 'Firefighter', 'https://www.youtube.com/watch?v=blMwY8Jabyk', 'Nutsa Buzalazde', 'Georgia'),
(25,'francia_bandera.webp', 'Mon Amour', 'https://www.youtube.com/watch?v=tfoOop2HXxQ', 'Slimane', 'Francia'),
(26,'austria_bandera.webp', 'We Will Rave', 'https://www.youtube.com/watch?v=Kqda15G4T-4', 'Kaleen', 'Austria');