INSERT INTO pais (id, bandera, cancion, cancion_youtube, cantante, nombre) VALUES
(1,'/bandera/suecia_bandera.webp', 'Unforgettable', 'https://www.youtube.com/watch?v=yekc8t0rJqA', 'Marcus & Martinus', 'Suecia'),
(2,'/bandera/ucrania_bandera.webp', 'Teresa & Maria', 'https://www.youtube.com/watch?v=k_8cNbF8FLI', 'alyona alyona & Jerry Heil', 'Ucrania'),
(3,'/bandera/alemania_bandera.webp', 'Always On The Run', 'https://www.youtube.com/watch?v=kVOHTxFOhak', 'Isaak', 'Alemania'),
(4,'/bandera/luxemburgo_bandera.webp', 'Fighter', 'https://www.youtube.com/watch?v=TCWH3Nq5y9A', 'TALI', 'Luxemburgo'),
(5,'/bandera/países_bajos_bandera.webp', 'Europapa', 'https://www.youtube.com/watch?v=gT2wY0DjYGo&list=RDEMyShnuIQ-pzWHcilvxBIPJw&start_radio=1', 'Joost Klein', 'Países Bajos'),
(6,'/bandera/israel_bandera.webp', 'Hurricane', 'https://www.youtube.com/watch?v=lJYn09tuPw4', 'Eden Golan', 'Israel'),
(7,'/bandera/lituania_bandera.webp', 'Luktelk', 'https://www.youtube.com/watch?v=N8YuQzJLR_k', 'Silvester Belt', 'Lituania'),
(8,'/bandera/españa_bandera.webp', 'Zorra', 'https://www.youtube.com/watch?v=LJFpexlj9Bs', 'Nebulossa', 'España'),
(9,'/bandera/estonia_bandera.webp', '(nendest) narkootikumidest ei tea me (küll) midagi', 'https://www.youtube.com/watch?v=zY6RbPaTNUc', '5miinust & Puuluup', 'Estonia'),
(10,'/bandera/irlanda_bandera.webp', 'Doomsday Blue', 'https://www.youtube.com/watch?v=ZGRXRrlIspY', 'Bambie Thug', 'Irlanda'),
(11,'/bandera/letonia_bandera.webp', 'Hollow', 'https://www.youtube.com/watch?v=p8FNO0DtBng&list=RDEMGCUTKht6npiEZIaO96FPFg&start_radio=1', 'Dons', 'Letonia'),
(12,'/bandera/grecia_bandera.webp', 'Zari', 'https://youtube.com/watch?v=XXXXX012', 'Marina Satti', 'Grecia'),
(13,'/bandera/reino_unido_bandera.webp', 'Dizzy', 'https://www.youtube.com/watch?v=uTYalXf184A', 'Olly Alexander', 'Reino Unido'),
(14,'/bandera/noruega_bandera.webp', 'Ulveham', 'https://www.youtube.com/watch?v=tFj0p2qIgdE', 'Gåte', 'Noruega'),
(15,'/bandera/italia_bandera.webp', 'La noia', 'https://www.youtube.com/watch?v=TO85laH-ATY', 'Angelina Mango', 'Italia'),
(16,'/bandera/serbia_bandera.webp', 'Ramonda', 'https://www.youtube.com/watch?v=tJyBVRBiyKA', 'Teya Dora', 'Serbia'),
(17,'/bandera/finlandia_bandera.webp', 'No Rules!', 'https://www.youtube.com/watch?v=8Wi7fhswoBA', 'Windows95man', 'Finlandia'),
(18,'/bandera/portugal_bandera.webp', 'Grito', 'https://www.youtube.com/watch?v=K5wDGhcDSpQ', 'Iolanda', 'Portugal'),
(19,'/bandera/armenia_bandera.webp', 'Jako', 'https://www.youtube.com/watch?v=Co8ZJIejXBA', 'Ladaniva', 'Armenia'),
(20,'/bandera/chipre_bandera.webp', 'Liar', 'https://www.youtube.com/watch?v=8q5QozrtEPA', 'Silia Kapsí', 'Chipre'),
(21,'/bandera/suiza_bandera.webp', 'The Code', 'https://www.youtube.com/watch?v=kiGDvM14Kwg', 'Nemo', 'Suiza'),
(22,'/bandera/eslovenia_bandera.webp', 'Veronika', 'https://www.youtube.com/watch?v=uWcSsi7SliI', 'Raiven', 'Eslovenia'),
(23,'/bandera/croacia_bandera.webp', 'Rim Tim Tagi Dim', 'https://www.youtube.com/watch?v=xTBrVNZtnys', 'Baby Lasagna', 'Croacia'),
(24,'/bandera/georgia_bandera.webp', 'Firefighter', 'https://www.youtube.com/watch?v=blMwY8Jabyk', 'Nutsa Buzalazde', 'Georgia'),
(25,'/bandera/francia_bandera.webp', 'Mon Amour', 'https://www.youtube.com/watch?v=tfoOop2HXxQ', 'Slimane', 'Francia'),
(26,'/bandera/austria_bandera.webp', 'We Will Rave', 'https://www.youtube.com/watch?v=Kqda15G4T-4', 'Kaleen', 'Austria');